JCN-112-Log
janis-commerce/log pull request #1
Opened 2019-07-26 12:51 UTC by Nataniel4

**JCN-112-LOG**
JCN-112 Crear paquete log

**LINK AL TICKET**
[https://fizzmod.atlassian.net/browse/JCN-112](url)

**DESCRIPCIÓN DEL REQUERIMIENTO**
1.1. Se requiere crear un paquete nuevo para la creación de logs
1.2. Los logs se deben crear en el servicio S3
1.3. Las credenciales aws_access_key_id y aws_secret_access_key se deben tomar de variables de entorno y que cada MS las tendrá configuradas.

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollo lo solicitado en el ticket

2019-07-30 13:20 UTC, juanhapes commented on README.md
>  # log
Dejemos la branch `master` directo porfa.

2019-07-30 13:20 UTC, juanhapes commented on lib/log.js
> +	static add(log, bucket) {
Me parece más correcto tener como 1er parámetro el nombre del bucket y en el 2do el log.

2019-07-30 13:20 UTC, juanhapes commented on lib/log.js
> +			date: log.date_created ? new Date(log.date_created * 1000) : new Date(),
Si se pidio extrictamente dejarlo igual, sino cambiar `date_created` por `dateCreated`

2019-07-30 13:20 UTC, juanhapes commented on tests/log-test.js
> +	it('should throw LogError when the Log is invalid or is empty', async () => {
Acá se esta testeando que throwee cuando sea un array vacío, el description no es correcto.
Debe ser algo como "... when the log given is an empty array"

Tema 2, faltan muchos casos de error:
- `Log.add(true, 'fooBucket');`
- `Log.add(54, 'fooBucket');`
- `Log.add(['foo', 'bar'], 'fooBucket');`
- `Log.add(null, 'fooBucket');`

-

2019-07-30 13:27 UTC, juanhapes commented on tests/log-test.js
> +	it('should throw LogError when the Log is invalid or is empty', async () => {
Para no tener que hacer multiples casos bloques `it()`, podes meter los casos invalidos en un array, recorrerlo y probar por cada valor.
En la description, podrias agrupar como "... when Log is not an object"

2019-07-30 13:27 UTC, juanhapes commented on tests/log-test.js
> +describe('Log', () => {
Al pasar siempre el dato `date_created`, nunca estas testeando el caso que esa fecha se cree sola automaticamente.

2019-08-05 16:15 UTC, jormaechea requested changes
Te dejé varios comentarios.
En mi opinión, hiciste código demasiado complejo para una tarea super simple: hacer una request con reintentos.

Con respecto a los tests: hubo un buen motivo para hacer un _"mock"_ de AWS con tanta complejidad? Alcanzaba con hacer algo como
```js
sandbox.stub(AWS, 'S3')
	.returns({
		putObject: someSinonStub
	});
```
y después assertear que se haya llamado a `someSinonStub` correctamente.
Hay mucha complejidad innecesaria ahí también

2019-08-05 16:15 UTC, jormaechea commented on lib/log.js
> +	accessKeyId: process.env.AWS_ACCESS_KEY_ID,
Acá no hace falta pasarle las keys. De hecho, cuando se ejecute en lambda no hay keys.
Simplemente no lo pasás, y en el `docker-compose.yml` se monta el siguiente volumen `- ~/.aws:/root/.aws`

**Ver el MS de router, que ya está implementado de esta manera.**

2019-08-05 16:15 UTC, jormaechea commented on lib/log.js
> +		const logDate = {
Perdón, pero qué necesidad de declarar un objeto con una prop y 3 getters, si se va a usar una sola vez, y los getters devuelven exactamente lo mismo cada vez que se los llama?

Es extremadamente más simple, fácil de entender y performante hacer simplemente
```js
const date = log.date_created ? new Date(log.date_created * 1000) : new Date();
const year = date.getFullYear();
const month = (date.getMonth() + 1).toString().padStart(2, 0);
const day = date.getDate().toString()
		.padStart(2, 0);
```

2019-08-05 16:15 UTC, jormaechea commented on lib/log.js
> +		S3.putObject({
Todos los métodos de los SDK de Amazon se pueden usar con Promise en lugar de callbacks.

Para este ejemplo, podés hacer algo asi:
```js
return S3.putObject({ ... }).promise();
```

Y del otro lado lo manejás con un `await`.
(Ver comentario sobre el método `add` de cómo simplificarlo)

2019-08-05 16:15 UTC, jormaechea commented on lib/log.js
> +	static add(bucket, log) {
Demasiado complejo para una tarea tan simple. Mirá qué simple se puede dejar todo esto, sin definir funciones adentro de funciones, con intervalos cuando ya le pusiste un timeout a la request.

```js
static async add(bucket, log, attempts = 0) {

	try {
		await this._add(bucket, log);
	} catch(err) {
		if(attempts >= MAX_ATTEMPTS)
			throw new LogError(`Unable to put the log into S3, max attempts reached: ${err.message}`, LogError.codes.S3_ERROR);

		return this.add(bucket, log, ++attempts);
	}
}
```

Por otro lado, en el catch podrías manejar la lógica de no hacer reintentos para los dos error codes `INVALID_BUCKET` y `INVALID_LOG`. No tiene sentido intentar guardar un log 3 veces si ya sabés que va a volver a fallar.

2019-08-05 16:15 UTC, jormaechea commented on lib/log.js
> +	accessKeyId: process.env.AWS_ACCESS_KEY_ID,
PD: Documentar en el README.

2019-08-06 15:35 UTC, jormaechea requested changes

2019-08-06 15:35 UTC, jormaechea commented on lib/log.js
> +const S3 = new AWS.S3({	httpOptions: { timeout: MAX_TIMEOUT } });
```suggestion
const S3 = new AWS.S3({ httpOptions: { timeout: MAX_TIMEOUT } });
```

2019-08-06 15:35 UTC, jormaechea commented on lib/log.js
> +				throw err;
Ojo con estos `throw`.. La aplicación no debería explotar por no poder guardar un log.
Por el momento, simplemente loggearía en la consola que no se pudo guardar el log, y el motivo.

2019-08-06 15:35 UTC, jormaechea commented on lib/log.js
> +				throw err;
Corrijo: no sé si loggear en la consola es una buena decisión en un package.
Quizás sea una mejor decisión emitir un evento de node.. 

Para eso, deberías crear un event emitter fuera de la clase
```js
const EventEmitter = require('events');
const emitter = new EventEmitter();
```

Y agregar un método `.on()` a la clase Log, que haga algo asi
```js
static on(event, callback) {
	emitter.on(event, callback);
}
```

Y finalmente, emitir el evento:
```js
emitter.emit('create-error', log, err);
```

---

Si alguien quisiera suscribirse a los errores al crear logs, haría algo asi:

```js
const Log = require('@janiscommerce/log');
Log.on('create-error', (log, err) => {
	// do something
});
```

2019-08-06 15:35 UTC, jormaechea commented on tests/log-test.js
> +MockRequire('aws-sdk', AWS);
Este MockRequire creería que no hace falta.
Por otro lado, un par de lineas más abajo estás creando un stub de `AWS.S3`, y nunca lo estás _restoreando_. Ojo ahí.

2019-08-06 15:35 UTC, jormaechea commented on tests/log-test.js
> +		sandbox.assert.callCount(putObjectStub, 4);
4 llamados? El máximo de intentos está setteado como 3..

2019-08-06 16:04 UTC, Nataniel4 commented on lib/log.js
> +const S3 = new AWS.S3({	httpOptions: { timeout: MAX_TIMEOUT } });
Que raro eso, no sale en el editor

2019-08-06 16:18 UTC, jormaechea commented on lib/log.js
> +const S3 = new AWS.S3({	httpOptions: { timeout: MAX_TIMEOUT } });
Debe coincidir el tab-stop justo en un caracter..

2019-08-07 16:37 UTC, jormaechea approved these changes

2019-08-07 16:38 UTC, merged