Jcn 277 sls configuration
janis-commerce/log pull request #12
Opened 2020-06-11 19:23 UTC by maguimarijuan

**Link al ticket**
https://fizzmod.atlassian.net/browse/JCN-277
**Descripción del requerimiento**
Se require agregar los hooks para el funcionamiento del paquete de log como un getter. Tambien se

2020-06-12 18:22 UTC, Nataniel4 commented on lib/firehose-instance.js
> +     * @returns
Falta poner que devuelve la instancia de firehose. Como sugerencia extra, se pueden sacar los `@static` y `@memberof` porque se sobreentienden esos puntos 👍

2020-06-12 18:25 UTC, Nataniel4 commented on CHANGELOG.md
> +- FirehoseInstace to cache the instance
typo [F] y hay algunos espacios dobles tambien #toc

2020-06-12 18:25 UTC, Nataniel4 requested changes
Comentarios chicos!

2020-06-12 20:25 UTC, Nataniel4 approved these changes
Aprobado!

2020-06-13 16:02 UTC, juanhapes requested changes
Cambios chicos pedidos en el README, de código todo bien :+1:

2020-06-13 16:02 UTC, juanhapes commented on README.md
> +const  Log = require('@janiscommerce/log');
Sobra un espacio
```suggestion
const Log = require('@janiscommerce/log');
```

2020-06-13 16:02 UTC, juanhapes commented on README.md
> +### Serverless configuration
Te parece si escribimos en 1 línea que es lo que estamos sumando y porqué es utl?
"Se puede agregar fácilmente la configuración... blablabla"

2020-07-29 18:31 UTC, merged