add janis trace private fields
janis-commerce/log pull request #13
Opened 2023-01-09 13:46 UTC by fedeatanasoff

**Contexto**
Actualmente en los logs de trace se esta dando visibilidad a datos sensibles como credenciales, lo cual es un problema. 

**Requisito**
Se requiere implementar un ajuste en el paquete de log [npm: @janiscommerce/log](https://www.npmjs.com/package/@janiscommerce/log) para empezar a excluir este tipo de información de los mismos.
Para lograr ello debemos crear una variable de entorno JANIS_TRACE_PRIVATE_FIELDS, en la cual definiremos los campos a excluir de los logs. En caso de que esta variable este presente, se debe excluir de los logs cada propiedad definida.

Ejemplo:
```
JANIS_TRACE_PRIVATE_FIELDS = ['credentials']

const log = {
    company: { 
        name: 'janis company',
        credentials: {
            username: 'user',
            password: 'password'
        }
}

// log a guardar 
log = {
    company: { 
        name: 'janis company'
}
```

2023-01-09 14:11 UTC, Nataniel4 requested changes

2023-01-09 14:11 UTC, Nataniel4 commented on package.json
> +    "lodash.omit": "^4.5.0",
Este parece que al final no lo usaste, se puede fletar? 🤔

2023-01-09 14:45 UTC, Nataniel4 approved these changes

2023-01-09 15:07 UTC, gastonpereyra commented on lib/helpers/utils.js
> +			if(Array.isArray(object[field]))
:warning: Que podria llegarte un

```
{
  name: 'soy un tests',
  date: [
    { password: '*********', user: 'test-user'},
    null,
    undefined
  ]
}
```

Y va a explotar todo

2023-01-09 15:09 UTC, gastonpereyra commented on lib/helpers/utils.js
> +			if(Array.isArray(object[field]))
El problema surge de confiar que `log` es un objeto no nulo, al principio de la función

2023-01-09 15:13 UTC, jormaechea commented on lib/helpers/utils.js
> +			if(Array.isArray(object[field]))
Aprovecho la volteada para comentar que una variable de entorno no tiene como ser un array.. Es siempre un string.. Habria que meterle un `split` por comas antes de usarlo como array..

2023-01-09 19:08 UTC, fedeatanasoff commented on lib/helpers/utils.js
> +			if(Array.isArray(object[field]))
en realidad no explotaba, pero cambiaba el `null` por un `{ }`..

ahi deje el caso de prueba del test con un objeto similar a este que pusiste

2023-01-09 19:35 UTC, gastonpereyra approved these changes

2023-01-09 21:38 UTC, jormaechea requested changes
@fedeatanasoff ojo que el caso default (sin env var) esta rompiendo..

2023-01-09 21:38 UTC, jormaechea commented on lib/helpers/utils.js
> +		return;
@fedeatanasoff Esto acá rompe, porque devuelve `undefined` y despues hace un `fieldsToExclude.includes()` y rompe. Agregate el caso de prueba donde la variable de entorno esta vacía y vas a ver que hay que ajustar..

![image](https://user-images.githubusercontent.com/5612500/211412824-ea7bf34b-a705-4e34-9bb9-c039ad18cada.png)

2023-01-10 13:50 UTC, fedeatanasoff commented on lib/helpers/utils.js
> +		return;
@jormaechea si es verdad, no lo contemple porque es un caso que nunca pasaría ya que si esa variable esta vacia ese método nunca se ejecutaría..
de todas formas meto eso y los casos de prueba para la función

2023-01-10 17:22 UTC, jormaechea approved these changes

2023-01-10 17:22 UTC, merged