JTR-57 firehose
janis-commerce/log pull request #6
Opened 2020-01-28 21:18 UTC by Nataniel4

**JTR-57-FIREHOSE**
JTR-57 Modificar el package log para usar Firehose en vez de S3

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JTR-57

**DESCRIPCIÓN DEL REQUERIMIENTO**
Las modificaciones solicitadas son:

- Eliminar la configuración de bucket
- En vez de usar AWS.S3 usar AWS.Firehose
- Donde envDeliveryStream debe ser
    - beta → JanisTraceFirehoseBeta
    - qa → JanisTraceFirehoseQA
    - prod → JanisTraceFirehoseProd
- La validación se debe hacer con superstruct
- Cambios de formato de log
    - type solo debe admitir String requerido
    - Se debe generar dateCreated en el momento, no se debe usar con el dato recibido en log
    - Crear el new Date() y luego formatearlo como UTC con toISOString()
    - Se debe agregar client en log.client, el dato se recibe en el primer parámetro del método 
      add(client, log).
    - Validar como String requerido
    - Validar userCreated como String opcional
    - En caso de re-intentar no se debe volver a formatear los datos, solo se debe re-intentar el putRecord()

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollaron los requerimientos solicitados

2020-02-10 19:01 UTC, maguimarijuan approved these changes

2020-02-11 13:36 UTC, gastonpereyra commented on lib/log.js
Sugerencia:
* Ordenar los métodos para mejor lectura

2020-02-11 13:39 UTC, gastonpereyra commented on lib/log.js
> +	static set deliveryStreamName(deliveryStreamName) {
Recomendación:
* Si no es un feature el poder cambiar el nombre del Stream no veo la necesidad de estos métodos, que habilitan a poder hacerlo.
* Si es un feature estaría bueno que estuviera en el Readme

2020-02-11 13:41 UTC, gastonpereyra commented on lib/log.js
> +		if(!this._env)
Sugerencia:
* Este chequeo lo haría en el método para formatear esta variable.

2020-02-11 14:00 UTC, gastonpereyra commented on lib/log.js
> +		this.deliveryStreamName = `${DELIVERY_STREAM_PREFIX}${this._getFormattedEnv()}`;
Esto podría ir directamente en el get, asi queda encapsulado

2020-02-11 14:06 UTC, gastonpereyra commented on lib/log.js
> +	static _buildLog(rawLog, client) {
Este método, hace 2 cosas, validate el log y lo arma.
Talvés estaría bueno que fueran 2 métodos:
* validaciones con el `struct`
* armado del log

En `add` podria quedar algo asi:

```js
	// ... code
	try {
		this.validate(log);
		log = this._buildLog(log, client);
	} catch(err) {
		return emitter.emit('create-error', log, err);
	}
	// ... more code
```

2020-02-11 14:07 UTC, gastonpereyra commented on package.json
> +    "superstruct": "0.6.1"
```suggestion
    "superstruct": "0.6.2"
```

2020-02-11 14:13 UTC, gastonpereyra commented on tests/log-test.js
> +		it('Should send a log to Firehose', async () => {
Faltaría un test que arme un log valido con variantes de los datos opcionales y los que se agregan por default

2020-02-11 14:13 UTC, gastonpereyra requested changes
Deje un par de comentarios

2020-02-12 15:14 UTC, gastonpereyra approved these changes

2020-02-12 20:03 UTC, juanhapes requested changes

2020-02-12 20:03 UTC, juanhapes commented on lib/log.js
> +	static _getFormattedEnv() {
No me parece buena esta solución. Propongo algo más directo para que quede mas prolijo, total ya se saben cuales son los ambientes:
```
static get _envs() {
	return {
		local: 'Local',
		beta: 'Beta',
		qa: 'QA',
		prod: 'Prod'
	};
}

static _getFormattedEnv() {
	if(!this._env || this._envs[this._env])
		throw new LogError('Unknown environment', LogError.codes.NO_ENVIRONMENT);

	return this._envs[this._env];
}
```

2020-02-12 20:03 UTC, juanhapes commented on lib/log.js
> +	static async _add(log, attempts = 1) {
Iniciemos _failedAttempts_ como 0, como primera linea del `catch()` hagamos `failedAttempts++` y luego a `_add()` se puede enviar directamente _failedAttempts_ sin modificar.
De esta forma, en **todo** momento _failedAttempts_ tiene los intentos fallidos reales, hoy _attempts_ no expresa la realidad casi en ningún momento :+1:

2020-02-14 17:56 UTC, merged